# make setup-minio
# docker compose --env-file .env.minio -f docker-compose.minio.yml up --build -d

name: pocketstream-minio

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    volumes:
      - $HOME/disks/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped

  pocketbase:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - $HOME/disks/fs/pb_data:/pb_data
      - $HOME/disks/fs/pb_backup:/pb_backup
    environment:
      - GOMEMLIMIT=${GOMEMLIMIT}
      - LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}
      - LITESTREAM_BACKUP_PATH=${LITESTREAM_BACKUP_PATH}
      - LITESTREAM_BUCKET=${LITESTREAM_BUCKET}
      - LITESTREAM_DB_PATH=${LITESTREAM_DB_PATH}
      - LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}
      - LITESTREAM_REGION=${LITESTREAM_REGION}
      - LITESTREAM_REPLICA_TYPE=${LITESTREAM_REPLICA_TYPE}
      - LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}
      - LITESTREAM_SKIP_VERIFY=${LITESTREAM_SKIP_VERIFY}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - POCKETBASE_ENCRYPTION_KEY=${POCKETBASE_ENCRYPTION_KEY}
      - PROFILE=docker
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED}
      - RATE_LIMIT_RULES=${RATE_LIMIT_RULES}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENABLED=${S3_ENABLED}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_USE_SSL=${S3_USE_SSL}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    depends_on:
      minio:
        condition: service_healthy

  litestream:
    build:
      context: .
      dockerfile: Dockerfile.litestream
    depends_on:
      - pocketbase
      - minio
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    volumes:
      - $HOME/disks/fs/pb_data:/pb_data
      - $HOME/disks/fs/pb_backup:/pb_backup
    environment:
      - LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}
      - LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}
      - LITESTREAM_BUCKET=${LITESTREAM_BUCKET}
      - LITESTREAM_REGION=${LITESTREAM_REGION}
      - LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}
      - LITESTREAM_SKIP_VERIFY=${LITESTREAM_SKIP_VERIFY}
      - LITESTREAM_REPLICA_TYPE=${LITESTREAM_REPLICA_TYPE:-file}
      - LITESTREAM_DB_PATH=${LITESTREAM_DB_PATH}
      - LITESTREAM_BACKUP_PATH=${LITESTREAM_BACKUP_PATH}
      - LITESTREAM_SYNC_INTERVAL=${LITESTREAM_SYNC_INTERVAL:-1s}
      - LITESTREAM_RETENTION=${LITESTREAM_RETENTION:-24h}
      - LITESTREAM_RETENTION_CHECK_INTERVAL=${LITESTREAM_RETENTION_CHECK_INTERVAL:-1h}
      - LITESTREAM_MONITOR_INTERVAL=${LITESTREAM_MONITOR_INTERVAL:-1s}
      - LITESTREAM_CHECKPOINT_INTERVAL=${LITESTREAM_CHECKPOINT_INTERVAL:-1m}
      - LITESTREAM_BUSY_TIMEOUT=${LITESTREAM_BUSY_TIMEOUT:-1s}
      - LITESTREAM_MIN_CHECKPOINT_PAGE_COUNT=${LITESTREAM_MIN_CHECKPOINT_PAGE_COUNT:-1000}
      - LITESTREAM_MAX_CHECKPOINT_PAGE_COUNT=${LITESTREAM_MAX_CHECKPOINT_PAGE_COUNT:-10000}
      - LITESTREAM_COMPRESS=${LITESTREAM_COMPRESS:-gzip}
      - LITESTREAM_MAX_WAL_BYTES=${LITESTREAM_MAX_WAL_BYTES:-512MB}
      - LITESTREAM_LOG_LEVEL=${LITESTREAM_LOG_LEVEL:-info}
      - LITESTREAM_LOG_TYPE=${LITESTREAM_LOG_TYPE:-text}
      - LITESTREAM_LOG_STDERR=${LITESTREAM_LOG_STDERR:-false}
    restart: unless-stopped