FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git ca-certificates build-base
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/litestream

FROM alpine:latest
RUN apk --no-cache add ca-certificates curl
COPY --from=litestream/litestream:latest /usr/local/bin/litestream /usr/local/bin/litestream
COPY --chmod=755 --from=builder /app/main /main

USER 1000:1000

ENTRYPOINT ["/main"]