FROM dxflrs/garage:v2.1.0 AS garage-bin

FROM golang:alpine AS builder

WORKDIR /app

COPY cmd/garage/main.go .

RUN go build -o garage main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=garage-bin /garage /usr/local/bin/garage

COPY --from=builder /app/garage /garage

COPY garage.toml /etc/garage.toml

WORKDIR /var/lib/garage

ENTRYPOINT ["/garage"]