# Use with docker-compose.common.yml
# docker compose -f docker-compose.common.yml -f docker-compose.minio.yml up

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 9
    restart: unless-stopped

  pocketstream:
    volumes:
      - pb_backup:/pb_backup
      - ./litestream.s3.yml:/etc/litestream.yml:ro
    environment:
      - LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}
      - LITESTREAM_BACKUP_PATH=${LITESTREAM_BACKUP_PATH}
      - LITESTREAM_BUCKET=${LITESTREAM_BUCKET}
      - LITESTREAM_COMPRESS=${LITESTREAM_COMPRESS}
      - LITESTREAM_DB_PATH=${LITESTREAM_DB_PATH}
      - LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}
      - LITESTREAM_MAX_WAL_BYTES=${LITESTREAM_MAX_WAL_BYTES}
      - LITESTREAM_REGION=${LITESTREAM_REGION}
      - LITESTREAM_REPLICA_TYPE=${LITESTREAM_REPLICA_TYPE}
      - LITESTREAM_RETENTION=${LITESTREAM_RETENTION}
      - LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}
      - LITESTREAM_SKIP_VERIFY=${LITESTREAM_SKIP_VERIFY}
      - LITESTREAM_SNAPSHOT_INTERVAL=${LITESTREAM_SNAPSHOT_INTERVAL}
      - LITESTREAM_SYNC_INTERVAL=${LITESTREAM_SYNC_INTERVAL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENABLED=${S3_ENABLED}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_USE_SSL=${S3_USE_SSL}
    depends_on:
      minio:
        condition: service_healthy

volumes:
  pb_data:
    external: true
  pb_backup:
    external: true
  s3_data:
    external: true