FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git ca-certificates build-base
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/litestream

FROM litestream/litestream:latest
COPY --from=builder /app/main /main
RUN chmod +x /main

USER 1000:1000

ENTRYPOINT ["/main"]