services:
  pocketstream:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data
    environment:
      - LITESTREAM_BACKUP_PATH=${LITESTREAM_BACKUP_PATH}
      - LITESTREAM_COMPRESS=${LITESTREAM_COMPRESS}
      - LITESTREAM_DB_PATH=${LITESTREAM_DB_PATH}
      - LITESTREAM_MAX_WAL_BYTES=${LITESTREAM_MAX_WAL_BYTES}
      - LITESTREAM_RETENTION=${LITESTREAM_RETENTION}
      - LITESTREAM_SNAPSHOT_INTERVAL=${LITESTREAM_SNAPSHOT_INTERVAL}
      - LITESTREAM_SYNC_INTERVAL=${LITESTREAM_SYNC_INTERVAL}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - POCKETBASE_ENCRYPTION_KEY=${POCKETBASE_ENCRYPTION_KEY}
      - PROFILE=docker
    restart: unless-stopped
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  pb_data:
    external: true