services:
  pocketbase:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/app/pb_data
      - pb_backup:/app/pb_backup
    environment:
      - APP_MODE=fs
      - APP_PROFILE=docker
      - POCKETBASE_ENCRYPTION_KEY=${POCKETBASE_ENCRYPTION_KEY}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
    command: ["serve", "--http=0.0.0.0:8090"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  litestream:
    image: litestream/litestream:latest
    command: replicate -config /etc/litestream.yml
    volumes:
      - pb_data:/app/pb_data
      - pb_backup:/app/pb_backup
      - ./litestream.yml:/etc/litestream.yml:ro
    environment:
      - LITESTREAM_DB_PATH=${LITESTREAM_DB_PATH}
      - LITESTREAM_BACKUP_PATH=${LITESTREAM_BACKUP_PATH}
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

volumes:
  pb_data:
    external: true
  pb_backup:
    external: true